---
editor_options: 
  markdown: 
    wrap: 72
output:
  github_document
---

```{r setup, echo = FALSE}
suppressPackageStartupMessages({
  library(readxl);
  library(stringr);
  library(dplyr)
})
```

# Docker/Singularity Setup

This project uses Docker (and Singularity, the TACC-equivalent version) for installation and version control of bioniformatics packages.
When installed correctly, these are invisible to the end-user.

## Installation on TACC

1. Setup your directories with `mkdir -p $WORK/singularity/bin`.
2. Copy `docker/singularity_mask.sh` to `$WORK/singularity`.
3. Edit your `.bashrc` to include `$WORK/singularity/bin` in your `$PATH`.
4. Prepare and run the singularity installation script:
```{bash, eval = FALSE, echo = TRUE}
cds hybrid_methylation/docker
mkdir logs
sbatch slurm/setup_singularity.slurm
```

This will install the singularity modules and configure them so that they can be used as regular bash commands.

## Setup brms/stan docker image on TACC

The cmdstan binaries will need to be compiled on TACC.

```{bash, eval = FALSE, echo = TRUE}
sbatch slurm/build_cmdstan.sh
```

## Optional: Setting up the brms/stan docker image locally

The Bayesian models use a docker image with brms and stan (edge-trait-meta) that initially created for a different project.

```{bash, eval = FALSE}
TAG=crpeters/edge-trait-meta:4.2.0 
sudo docker pull $TAG

# Configure the image:
# Set the working directory as your current directory (the project root)
LOCAL_DIR=$PWD 
CONF_DIR=$LOCAL_DIR/setup/docker/prefs
# If you'd like to access the git repo from within the image, mount your ssh directory
mkdir $CONF_DIR
# Otherwise, comment this line out
SSH_MOUNT="-v $HOME/.ssh:/home/rstudio/.ssh "
INTERNAL_NAME='hybrid_methylation'

NAME=r-brms
PORT=8784
# Run the container
sudo docker run -d -p 127.0.0.1:$PORT:8787 \
-v $LOCAL_DIR:/home/rstudio/${INTERNAL_NAME} \
-v $CONF_DIR:/home/rstudio/.config/rstudio \
$SSH_MOUNT \
-e DISABLE_AUTH=true -e USERID=$UID --name $NAME $TAG
```

Note that this will configure RStudio Server to run without authentication.
If you're running this on a local machine, this is the easiest option; however, running it on a resource that is accessible from the web would be a security vulnerability.
In this case, replace `-e DISABLE_AUTH=true` with `-e PASSWORD=...` (where the dots are your password). 

You'll need to install cmdstan in a mounted location once you've launched docker.

### Using the brms Docker Image locally

In the console, run `sudo docker container start edge_trait_meta` (you can skip this if you just initialized the container).  Then, open a web browser and go to [localhost:8784](localhost:8784) (Change the last number to whatever $PORT is if you adjust it).  

When you're done, run `sudo docker container stop edge_trait_meta` to shut it down.

## If there are errors

There are occasional issues with downloading these docker images on singularity. This appears to be some sort of privacy/authorization problem. If someone wants to download these images and gets any errors, contact me (Christopher) I'll help figure it out. You can also build the images yourself on a local system from the provided dockerfiles.


